name: food_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  mocktail: ^0.3.0
  network_image_mock: ^2.1.1
  shimmer: ^2.0.0
  bloc_test: ^9.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
